version: '3.7'
services:
  superset:
    build: .
    container_name: superset
    ports:
      - "8088:8088"
    restart: always
  mysql:
    image: mysql:8.0
    container_name: superset_mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: superset
      MYSQL_DATABASE: superset