version: '3'
services:
  superset:
    build: superset/.
    container_name: superset
    ports:
      - "8088:8088"
    env_file:
      - ./superset/env_file
    depends_on:
      - db
  db:
    build: db/.
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: passw0rd
    volumes:
      - ./db/conf.d:/etc/mysql/conf.d
      - ./db/entrypoint:/docker-entrypoint-initdb.d
  cache:
    image: redis:7
    container_name: cache

